### ISSUE TITLE
BUG: ItemPinRequestInvalidAngleOrSizeType

### ISSUE THREAD

**Issue by HugoVG** [FomTarro/VTS-Sharp#39]
ErrorID - ItemPinRequestInvalidAngleOrSizeType

it doesn't matter which combination of ``VTSItemAngleRelativityMode`` and ``VTSItemSizeRelativityMode``, size or angle it'll always return this error when dynamically pinning objects.

any way you got this working?
code:

```cs
 // Load the item
        var item = await plugin.VTSPlugin.LoadItem(prop.fileName, new VTSCustomDataItemLoadOptions()
        {
            positionX = 0,
            positionY = 0,
        });
        
        //get Item info
        var itemInstanceId = item.data.instanceID;
        // Get Current Model Info
        var model = await plugin.VTSPlugin.GetCurrentModel();
        
        // Get a list of artmeshes
        var artMeshes = await plugin.VTSPlugin.GetArtMeshList();
        
        // Get the first artmesh
        var artMesh = artMeshes.data.artMeshNames.FirstOrDefault();

        // Model Id and ArtMesh Id left empty for random
        await plugin.VTSPlugin.PinItemToRandom(itemInstanceId, "", "", 1,
            VTSItemAngleRelativityMode.RelativeToPinPosition, 
1, 
VTSItemSizeRelativityMode.RelativeToCurrentItemSize);  // Lots of expermentation 

```

**Comment by FomTarro** [comment]
Acknowledged, will investigate ASAP.

**Comment by FomTarro** [comment]
My immediate guess is that the various Mode enums are getting serialized to `int` values instead of to their `string` names. You may be able to get a temporary fix faster than me by:

1. Updating the Pin Request data model to have these properties as strings instead of enums.
2. Creating a helper method to convert the enums to strings.
3. Inserting this helper method in the various Pin request methods in the core plugin class.

**Comment by HugoVG** [comment]
that doesn't seem the case
```json
{
  "data": {
    "pin": true,
    "itemInstanceID": "f092a7dd63894b54bff172147b8c6098",
    "angleRelativeTo": "RelativeToPinPosition",
    "sizeRealtiveTo": "RelativeToCurrentItemSize",
    "vertexPinType": "Random",
    "pinInfo": {
      "modelID": "",
      "artMeshID": "",
      "angle": 1,
      "size": 1,
      "vertexID1": 0,
      "vertexID2": 0,
      "vertexID3": 0,
      "vertexWeight1": 0,
      "vertexWeight2": 0,
      "vertexWeight3": 0
    }
  },
  "apiName": "VTubeStudioPublicAPI",
  "timestamp": 0,
  "apiVersion": "1.0",
  "requestID": "c082012c-8a0c-415e-aa35-a1062f36a7ba",
  "messageType": "ItemPinRequest"
}
```

**Comment by FomTarro** [comment]
Thank you for being able to check that so quickly. `RelativeToPinPosition` and `RelativeToCurrentItemSize` are both listed as valid values on the API, so I'm not immediately sure what the issue is. I have messaged @DenchiSoft to see if he knows.

https://github.com/DenchiSoft/VTubeStudio?tab=readme-ov-file#options-for-pinning

**Comment by DenchiSoft** [comment]
There's a typo in your payload: `sizeRealtiveTo` should be `sizeRelativeTo`

**Comment by HugoVG** [comment]
Made a PR to change it #40

**Comment by FomTarro** [comment]
D'oh! I am so sorry for my illiteracy! I was so focused on the values being valid that I failed to consider the keys...

Thank you both.
